tasks:
  - init: |
     npm install
     npm run start
    
vscode:
  extensions:
    - astro-build.astro-vscode
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    
ports:
  - port: 3000
    onOpen: open-browser
